version: "3.9"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - .:/app

networks:
  mynetwork:
