name: Docker Build

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        docker build -t $DOCKER_USER/hb_dashboard_front .
    - name: Push the Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOCKER_USER/hb_dashboard_front