name: Docker frontend

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_CONFIG: ${{ github.workspace }}/.docker

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure Docker credentials
      run: |
        mkdir $DOCKER_CONFIG
        echo -n "$DOCKER_PASSWORD" | docker --config $DOCKER_CONFIG login --username $DOCKER_USER --password-stdin
    - name: Build the Frontend image
      run: |
        docker build -t $DOCKER_USER/hb_dashboard_front .
    - name: Push the Frontend image
      run: |
        docker --config $DOCKER_CONFIG push $DOCKER_USER/hb_dashboard_front